version: "3.8"

services:
  rust:
    container_name: rust
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    env_file:
      - ./apps/backend/.env
    ports:
      - "8080:8080"
    volumes:
      - ./apps/backend:/apps/backend
